[package]
name = "snowflake_arrow"
version = "0.1.0"
edition = "2021"
authors = ["Josh Taylor <joshuataylorx@gmail.com>"]

[lib]
name = "snowflake_arrow"
path = "src/lib.rs"
crate-type = ["rlib", "dylib"]

[dependencies]
rustler = "0.25.0"
arrow2 = { git = "https://github.com/jorgecarleitao/arrow2", features = ["io_ipc", "simd"] }
bytes = "1"
chrono = "0.4"
indexmap = "1.8.2"

[profile.release]
lto = true
codegen-units = 1