[package]
name = "snowflake_arrow"
version = "0.1.0"
edition = "2021"
authors = ["Josh Taylor <joshuataylorx@gmail.com>"]

[lib]
name = "snowflake_arrow"
path = "src/lib.rs"
crate-type = ["rlib", "dylib"]

[dependencies]
rustler = "0.25.0"
arrow2 = { version = "0.12", features = ["io_ipc", "simd"] }
rayon = "1.5"
chrono = "0.4"
streaming-iterator = { version = "0.1" }

[profile.release]
lto = true
codegen-units = 1