[package]
name = "snowflake_arrow"
version = "0.1.0"
edition = "2021"
authors = ["Josh Taylor <joshuataylorx@gmail.com>"]

[lib]
name = "snowflake_arrow"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.25.0"
arrow2 = { version  = "0.12.0", features = ["io_ipc", "simd"] }
chrono = "0.4"
rayon = "1.5.3"
indexmap = {version = "1.8.2", features = ["rayon"]}

[profile.release]
lto = true
codegen-units = 1